version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:10"
      timezone: America/La_Paz
    open-pull-requests-limit: 5
    labels:
      - dependencies
