<script setup>
import { onMounted, ref } from 'vue'
import { useQuasar } from 'quasar'
import { api } from '../boot/axios'
import PageHeader from '../components/PageHeader.vue'

const $q=useQuasar(); const loading=ref(true); const rows=ref([]); const status=ref('pendiente'); const generated=ref(null); const siteOrigin=window.location.origin
const statusOptions=[{label:'Pendientes',value:'pendiente'},{label:'En revisión',value:'en_revision'},{label:'Aprobadas',value:'aprobada'},{label:'Rechazadas',value:'rechazada'}]
const statusColor=v=>({pendiente:'orange',en_revision:'primary',aprobada:'positive',rechazada:'negative'}[v]||'grey')
const statusLabel=v=>({pendiente:'Pendiente',en_revision:'En revisión',aprobada:'Aprobada',rechazada:'Rechazada'}[v]||v)
const invitationColor=v=>({pendiente:'orange',usada:'positive',revocada:'negative',vencida:'grey'}[v]||'grey')
const invitationLabel=v=>({pendiente:'Disponible',usada:'Utilizada',revocada:'Revocada',vencida:'Vencida'}[v]||v||'Sin invitación')
const planLabel=row=>row.plan?.nombre||row.plan_codigo||'Sin plan seleccionado'
const billingLabel=row=>row.modalidad==='anual'?'Anual':row.modalidad==='mensual'?'Mensual':'Por definir'
async function load(){loading.value=true;try{const r=await api.get('/accesos',{params:{estado:status.value,per_page:100}});rows.value=r.data?.data?.data||[]}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudieron cargar las solicitudes de acceso.'})}finally{loading.value=false}}
function markReview(row){$q.dialog({title:'Tomar solicitud en revisión',message:`¿Marcar la solicitud de ${row.nombre} (${row.negocio}) como en revisión?`,cancel:true,persistent:true}).onOk(async()=>{try{await api.post(`/accesos/${row.id}/revision`);$q.notify({type:'positive',message:'La solicitud quedó en revisión.'});await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo actualizar la solicitud.'})}})}
function approve(row){$q.dialog({title:'Aprobar solicitud',message:`¿Crear un acceso personal para ${row.nombre} (${row.negocio})?`,prompt:{model:'7',type:'number',label:'Vigencia en días'},cancel:true,persistent:true}).onOk(async days=>{try{const r=await api.post(`/accesos/${row.id}/aprobar`,{dias_vigencia:Number(days)||7});generated.value=r.data?.data||null;$q.notify({type:'positive',message:r.data?.message||'Acceso generado.'});await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo aprobar la solicitud.'})}})}
function reject(row){$q.dialog({title:'Rechazar solicitud',message:`Indica por qué no se aprueba la solicitud de ${row.nombre}.`,prompt:{model:'',type:'textarea',isValid:v=>String(v||'').trim().length>=5},cancel:true,persistent:true}).onOk(async reason=>{try{await api.post(`/accesos/${row.id}/rechazar`,{notas:reason});$q.notify({type:'positive',message:'Solicitud rechazada.'});await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo rechazar la solicitud.'})}})}
async function copy(text,label){try{await navigator.clipboard.writeText(text);$q.notify({type:'positive',message:`${label} copiado.`})}catch{$q.notify({type:'warning',message:'No se pudo copiar automáticamente.'})}}
onMounted(load)
</script>
<template>
  <q-page class="viti-page q-pa-lg">
    <PageHeader title="Solicitudes de acceso" subtitle="Controla las solicitudes de entrada a VITI y genera invitaciones personales desde un único lugar." />
    <div class="row items-center q-col-gutter-md q-mt-lg"><div class="col-12 col-md-5"><q-select v-model="status" outlined emit-value map-options :options="statusOptions" label="Estado" @update:model-value="load" /></div><div class="col-12 col-md-auto q-ml-auto"><q-btn outline color="primary" icon="refresh" label="Actualizar" no-caps @click="load" /></div></div>
    <q-card v-if="generated" flat bordered class="q-mt-lg generated-card"><q-card-section><div class="row items-start no-wrap"><q-avatar color="green-1" text-color="positive" icon="verified"/><div class="q-ml-md col"><div class="text-subtitle1 text-weight-bold">Acceso generado</div><div class="text-body2 text-grey-7">Comparte el código o enlace. La invitación conserva su vencimiento y el registro seguro existente.</div><div class="generated-code q-mt-md">{{generated.codigo}}</div><div class="text-caption text-grey-6 q-mt-xs">Vence: {{generated.expira_at?new Date(generated.expira_at).toLocaleString('es-BO'):'—'}}</div><div class="row q-gutter-sm q-mt-md"><q-btn unelevated color="primary" no-caps icon="content_copy" label="Copiar código" @click="copy(generated.codigo,'Código')"/><q-btn flat color="primary" no-caps icon="link" label="Copiar enlace" @click="copy(`${siteOrigin}${generated.ruta}`,'Enlace')"/></div></div><q-btn flat round dense icon="close" @click="generated=null"/></div></q-card-section></q-card>
    <q-card flat bordered class="q-mt-lg"><q-table :rows="rows" :columns="[{name:'persona',label:'Solicitante',field:'nombre',align:'left'},{name:'negocio',label:'Negocio',field:'negocio',align:'left'},{name:'plan',label:'Preferencia',field:'plan_codigo',align:'left'},{name:'contacto',label:'Contacto',field:'telefono',align:'left'},{name:'acceso',label:'Acceso',field:'invitacion_id',align:'left'},{name:'estado',label:'Estado',field:'estado',align:'left'},{name:'fecha',label:'Fecha',field:'created_at',align:'left'},{name:'acciones',label:'',field:'id',align:'right'}] :loading="loading" row-key="id" flat no-data-label="No hay solicitudes en este estado."><template #body-cell-persona="p"><q-td :props="p"><div class="text-weight-bold">{{p.row.nombre}}</div><div class="text-caption text-grey-6">{{p.row.actividad||'Actividad no indicada'}}</div></q-td></template><template #body-cell-plan="p"><q-td :props="p"><div class="text-weight-medium">{{planLabel(p.row)}}</div><div class="text-caption text-grey-6">{{billingLabel(p.row)}}</div></q-td></template><template #body-cell-acceso="p"><q-td :props="p"><template v-if="p.row.invitacion"><q-badge rounded :color="invitationColor(p.row.invitacion.estado)" :label="invitationLabel(p.row.invitacion.estado)"/><div class="text-caption text-weight-bold q-mt-xs">{{p.row.invitacion.codigo||'—'}}</div><div class="text-caption text-grey-6">{{p.row.invitacion.expira_at?new Date(p.row.invitacion.expira_at).toLocaleDateString('es-BO'):'—'}}</div></template><span v-else class="text-caption text-grey-6">Sin invitación</span></q-td></template><template #body-cell-estado="p"><q-td :props="p"><q-badge rounded :color="statusColor(p.row.estado)" :label="statusLabel(p.row.estado)"/></q-td></template><template #body-cell-fecha="p"><q-td :props="p">{{new Date(p.row.created_at).toLocaleString('es-BO')}}</q-td></template><template #body-cell-acciones="p"><q-td :props="p"><div v-if="['pendiente','en_revision'].includes(p.row.estado)" class="row justify-end q-gutter-xs"><q-btn v-if="p.row.estado==='pendiente'" flat round dense color="primary" icon="visibility" @click="markReview(p.row)"/><q-btn flat round dense color="positive" icon="check" @click="approve(p.row)"/><q-btn flat round dense color="negative" icon="close" @click="reject(p.row)"/></div></q-td></template></q-table></q-card>
  </q-page>
</template>
<style scoped>.generated-card{border-color:color-mix(in srgb,#21ba45 35%,var(--viti-border));background:var(--viti-card)}.generated-code{display:inline-block;padding:12px 16px;border-radius:12px;background:#0b2436;color:#fff;font-size:22px;font-weight:900;letter-spacing:.08em}</style>
