<script setup>
import { computed, onMounted, ref } from 'vue'
import { useQuasar } from 'quasar'
import { api } from '../boot/axios'
import { downloadFile } from '../utils/download'
import PageHeader from '../components/PageHeader.vue'
import { formatDateTime } from '../utils/date'
const $q=useQuasar(),rows=ref([]),loading=ref(false),dialog=ref(false),type=ref('empresa'),entityId=ref(null),category=ref('general'),description=ref(''),file=ref(null)
const catalogs=ref({cliente:[],empresa:[],solicitud:[],proyecto:[],aplicacion:[]})
const typeOptions=[{label:'Cliente',value:'cliente'},{label:'Empresa',value:'empresa'},{label:'Solicitud',value:'solicitud'},{label:'Proyecto',value:'proyecto'},{label:'Aplicación',value:'aplicacion'}]
const entityOptions=computed(()=>catalogs.value[type.value].map(x=>({label:x.label,value:x.id})))
const columns=[{name:'nombre_original',label:'Archivo',field:'nombre_original',align:'left'},{name:'categoria',label:'Categoría',field:'categoria',align:'left'},{name:'descripcion',label:'Descripción',field:'descripcion',align:'left'},{name:'usuario',label:'Subido por',field:r=>r.usuario?`${r.usuario.nombre} ${r.usuario.apellido||''}`:'',align:'left'},{name:'created_at',label:'Fecha',field:r=>formatDateTime(r.created_at),align:'left'},{name:'actions',label:'',field:'actions',align:'right'}]
async function load(){loading.value=true;try{const [a,c,e,s,p,apps]=await Promise.all([api.get('/archivos',{params:{per_page:100}}),api.get('/clientes',{params:{per_page:100}}),api.get('/empresas',{params:{per_page:100}}),api.get('/solicitudes',{params:{per_page:100}}),api.get('/proyectos',{params:{per_page:100}}),api.get('/aplicaciones',{params:{per_page:100}})]);rows.value=a.data.data;catalogs.value={cliente:c.data.data.map(x=>({id:x.id,label:x.nombre})),empresa:e.data.data.map(x=>({id:x.id,label:x.nombre_comercial})),solicitud:s.data.data.map(x=>({id:x.id,label:`${x.codigo} · ${x.titulo}`})),proyecto:p.data.data.map(x=>({id:x.id,label:`${x.codigo} · ${x.nombre}`})),aplicacion:apps.data.data.map(x=>({id:x.id,label:x.nombre}))}}finally{loading.value=false}}
function open(){type.value='empresa';entityId.value=null;category.value='general';description.value='';file.value=null;dialog.value=true}
async function upload(){try{const fd=new FormData();fd.append('tipo',type.value);fd.append('id',entityId.value);fd.append('categoria',category.value);fd.append('descripcion',description.value||'');fd.append('archivo',file.value);await api.post('/archivos',fd);$q.notify({type:'positive',message:'Archivo subido.'});dialog.value=false;load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo subir.'})}}
function remove(row){$q.dialog({title:'Eliminar archivo',message:`¿Eliminar ${row.nombre_original}?`,cancel:true}).onOk(async()=>{await api.delete(`/archivos/${row.id}`);load()})}
onMounted(load)
</script>
<template><q-page class="viti-page"><PageHeader eyebrow="Soporte documental" title="Archivos e imágenes" subtitle="Adjunta logotipos, capturas, documentos, referencias, actas y evidencias a cualquier proceso."><q-btn color="primary" unelevated icon="upload_file" label="Subir archivo" no-caps @click="open"/></PageHeader><q-table flat class="viti-table" :rows="rows" :columns="columns" row-key="id" :loading="loading" :pagination="{rowsPerPage:20,sortBy:'id',descending:true}"><template #body-cell-actions="p"><q-td :props="p"><q-btn flat round dense icon="download" color="primary" @click="downloadFile(`/archivos/${p.row.id}/descargar`,p.row.nombre_original)"/><q-btn flat round dense icon="delete_outline" color="negative" @click="remove(p.row)"/></q-td></template><template #no-data><div class="empty-state full-width"><q-icon name="folder_open" size="52px"/><div class="text-h6 q-mt-sm">No hay archivos</div><div>Sube imágenes, PDFs o documentos relacionados con tus clientes y proyectos.</div></div></template></q-table>
<q-dialog v-model="dialog"><q-card style="width:660px;max-width:94vw"><q-card-section><div class="section-label">Nuevo archivo</div><div class="text-h5 text-weight-bold">Adjuntar documento o imagen</div></q-card-section><q-card-section><div class="row q-col-gutter-md"><div class="col-12 col-sm-5"><q-select v-model="type" outlined emit-value map-options :options="typeOptions" label="Relacionado con *" @update:model-value="entityId=null"/></div><div class="col-12 col-sm-7"><q-select v-model="entityId" outlined emit-value map-options :options="entityOptions" label="Registro *"/></div><div class="col-12 col-sm-5"><q-select v-model="category" outlined :options="['general','logo','referencia','requerimiento','diseño','captura','contrato','entrega','respaldo']" label="Categoría"/></div><div class="col-12 col-sm-7"><q-file v-model="file" outlined label="Archivo *" accept=".jpg,.jpeg,.png,.webp,.pdf,.doc,.docx,.xls,.xlsx,.txt,.zip"/></div><div class="col-12"><q-input v-model="description" outlined type="textarea" label="Descripción"/></div></div></q-card-section><q-card-actions align="right"><q-btn flat label="Cancelar" v-close-popup/><q-btn color="primary" unelevated label="Subir archivo" no-caps :disable="!entityId||!file" @click="upload"/></q-card-actions></q-card></q-dialog></q-page></template>
