<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { api } from '../boot/axios'
import PageHeader from '../components/PageHeader.vue'

const router=useRouter();const loading=ref(true);const apps=ref([])
const available=computed(()=>apps.value.filter(app=>['activa','gracia','suspendida'].includes(app.estado_servicio)))
const pending=computed(()=>apps.value.filter(app=>!['activa','gracia','suspendida'].includes(app.estado_servicio)))
function pretty(v){return String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function openApp(app){if(app.ruta)router.push(app.ruta)}
function color(state){return({activa:'positive',gracia:'orange',suspendida:'negative',lista_entrega:'teal',pruebas:'purple',preparacion:'blue',cancelada:'grey'}[state]||'grey')}
function icon(app){return app.catalogo?.icono||'apps'}
onMounted(async()=>{try{apps.value=(await api.get('/mi/aplicaciones')).data.data||[]}finally{loading.value=false}})
</script>
<template><q-page class="viti-page"><q-inner-loading :showing="loading"/><PageHeader eyebrow="Mi espacio VITI" title="Mis aplicaciones" subtitle="Aplicaciones disponibles y en preparación para el negocio seleccionado."/>
<template v-if="!loading"><div v-if="available.length" class="apps-grid"><q-card v-for="app in available" :key="app.id" flat class="viti-card app-card"><q-card-section class="row items-start no-wrap q-gutter-md"><q-avatar size="58px" color="primary" text-color="white" :icon="icon(app)"/><div class="col"><div class="row items-center q-gutter-sm"><div class="text-h6 text-weight-bold">{{app.catalogo?.nombre||app.nombre}}</div><q-badge :color="color(app.estado_servicio)">{{pretty(app.estado_servicio)}}</q-badge><q-badge v-if="app.es_externa" outline color="primary">Vercel integrado</q-badge></div><div class="text-body2 text-grey-7 q-mt-xs">{{app.empresa?.nombre_comercial}}</div><div class="text-caption text-grey-6 q-mt-sm">{{app.version?`Versión ${app.version} · `:''}}{{app.estado_mensaje}}</div><div v-if="app.suscripcion" class="text-caption q-mt-xs" :class="app.estado_servicio==='suspendida'?'text-negative':'text-grey-6'">{{Number(app.suscripcion.monto||0).toFixed(2)}} Bs / {{app.suscripcion.frecuencia==='anual'?'año':'mes'}} · vence {{app.suscripcion.fecha_vencimiento}}</div></div></q-card-section><q-banner v-if="app.estado_servicio==='gracia'" class="bg-orange-1 text-orange-10">La aplicación sigue disponible durante el periodo de gracia.</q-banner><q-banner v-if="app.estado_servicio==='suspendida'" class="bg-red-1 text-negative">Acceso suspendido temporalmente. Los datos del negocio permanecen guardados.</q-banner><q-separator/><q-card-actions align="between" class="q-pa-md"><div class="text-caption text-grey-6">{{app.es_externa?'Sistema integrado':'VITI App'}}</div><div class="row q-gutter-sm"><q-btn v-if="app.estado_servicio==='suspendida'" outline color="primary" no-caps icon="payments" label="Ver pagos" to="/mi-pagos"/><q-btn color="primary" unelevated no-caps icon-right="arrow_forward" :label="app.es_externa?'Abrir dentro de VITI':'Abrir aplicación'" :disable="!app.ruta" @click="openApp(app)"/></div></q-card-actions></q-card></div>
<q-card v-if="pending.length" flat class="viti-card q-mt-lg"><q-card-section><div class="text-h6 text-weight-bold">En preparación</div><div class="text-caption text-grey-6">Puedes seguir el estado sin entrar todavía a la aplicación.</div></q-card-section><q-separator/><q-list separator><q-item v-for="app in pending" :key="app.id"><q-item-section avatar><q-avatar color="grey-2" text-color="grey-7" :icon="icon(app)"/></q-item-section><q-item-section><q-item-label class="text-weight-bold">{{app.catalogo?.nombre||app.nombre}}</q-item-label><q-item-label caption>{{app.estado_mensaje}}{{app.proyecto?` · ${app.proyecto.progreso||0}% del proyecto`:''}}</q-item-label></q-item-section><q-item-section side><q-badge outline :color="color(app.estado_servicio)">{{pretty(app.estado_servicio)}}</q-badge></q-item-section></q-item></q-list></q-card>
<div v-if="!apps.length" class="empty-state"><q-icon name="apps" size="58px"/><div class="text-h6 q-mt-md">Todavía no tienes aplicaciones</div><div class="q-mt-xs">Puedes revisar el Catálogo VITI o seguir el avance de tu proyecto.</div><q-btn class="q-mt-lg" color="primary" unelevated no-caps icon="widgets" label="Ver Catálogo VITI" to="/catalogo-viti"/></div></template></q-page></template>
<style scoped>.apps-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(310px,460px));gap:18px}.app-card{overflow:hidden}.empty-state{min-height:320px;display:flex;flex-direction:column;align-items:center;justify-content:center;color:var(--viti-muted);text-align:center}</style>
