<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { useQuasar } from 'quasar'
import { api } from '../boot/axios'
import { useTenantStore } from '../stores/tenant'
import PageHeader from '../components/PageHeader.vue'

const $q = useQuasar()
const tenant = useTenantStore()
const loading = ref(true)
const saving = ref(false)
const info = ref(null)
const team = ref([])
const dialog = ref(false)
const editing = ref(null)
const form = reactive({ nombre_comercial:'',razon_social:'',actividad:'',telefono:'',whatsapp:'',ciudad:'',direccion:'',moneda:'BOB',zona_horaria:'America/La_Paz' })
const member = reactive({ nombre:'',apellido:'',usuario:'',telefono:'',password:'',rol_negocio:'empleado',activo:true })
const canManage = computed(() => !!info.value?.puede_administrar)
const roles = [{label:'Propietario',value:'propietario'},{label:'Administrador',value:'administrador'},{label:'Empleado',value:'empleado'}]
const columns=[{name:'persona',label:'Usuario',field:'nombre',align:'left'},{name:'rol',label:'Rol',field:'rol_negocio',align:'left'},{name:'estado',label:'Estado',field:'activo',align:'left'},{name:'acciones',label:'',field:'id',align:'right'}]

function pretty(v){return String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
async function load(){loading.value=true;try{if(!tenant.loaded) await tenant.load(); const {data}=await api.get('/mi/negocio');info.value=data.data;Object.assign(form,data.data.empresa||{});if(data.data.puede_administrar){team.value=(await api.get('/mi/negocio/equipo')).data.data||[]}else team.value=[]}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo cargar el negocio.'})}finally{loading.value=false}}
async function save(){saving.value=true;try{await api.put('/mi/negocio',form);$q.notify({type:'positive',message:'Negocio actualizado.'});await tenant.load();await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo guardar.'})}finally{saving.value=false}}
async function uploadLogo(event){const file=event.target.files?.[0];if(!file)return;const body=new FormData();body.append('logo',file);try{await api.post('/mi/negocio/logo',body,{headers:{'Content-Type':'multipart/form-data'}});$q.notify({type:'positive',message:'Logo actualizado.'});await tenant.load();await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo subir el logo.'})}finally{event.target.value=''}}
function newMember(){editing.value=null;Object.assign(member,{nombre:'',apellido:'',usuario:'',telefono:'',password:'',rol_negocio:'empleado',activo:true});dialog.value=true}
function editMember(row){editing.value=row;Object.assign(member,{nombre:row.nombre,apellido:row.apellido||'',usuario:row.usuario,telefono:row.telefono||'',password:'',rol_negocio:row.rol_negocio,activo:row.activo});dialog.value=true}
async function saveMember(){try{if(editing.value)await api.put(`/mi/negocio/equipo/${editing.value.id}`,{rol_negocio:member.rol_negocio,activo:member.activo,password:member.password||null});else await api.post('/mi/negocio/equipo',member);dialog.value=false;$q.notify({type:'positive',message:editing.value?'Acceso actualizado.':'Usuario agregado.'});await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||Object.values(e.response?.data?.errors||{}).flat()[0]||'No se pudo guardar el usuario.'})}}
async function removeMember(row){if(!confirm(`¿Quitar el acceso de ${row.nombre}?`))return;try{await api.delete(`/mi/negocio/equipo/${row.id}`);await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo quitar el acceso.'})}}
function tenantChanged(){load()}
onMounted(()=>{load();window.addEventListener('viti-tenant-changed',tenantChanged)})
onBeforeUnmount(()=>window.removeEventListener('viti-tenant-changed',tenantChanged))
</script>

<template><q-page class="viti-page"><PageHeader eyebrow="Mi espacio VITI" title="Mi negocio" subtitle="Configura los datos del negocio y controla quién puede trabajar en él."/><q-inner-loading :showing="loading"/>
<div v-if="!loading" class="row q-col-gutter-lg"><div class="col-12 col-lg-7"><q-card flat class="viti-card"><q-card-section class="row items-center"><div><div class="text-h6 text-weight-bold">Datos del negocio</div><div class="text-caption text-grey-6">Rol actual: {{pretty(info?.rol)}}</div></div><q-space/><label v-if="canManage" class="cursor-pointer"><q-btn outline color="primary" no-caps icon="image" label="Cambiar logo"/><input hidden type="file" accept="image/png,image/jpeg,image/webp" @change="uploadLogo"/></label></q-card-section><q-separator/><q-card-section><div class="row q-col-gutter-md"><div class="col-12 col-sm-6"><q-input v-model="form.nombre_comercial" outlined label="Nombre comercial" :disable="!canManage"/></div><div class="col-12 col-sm-6"><q-input v-model="form.razon_social" outlined label="Razón social" :disable="!canManage"/></div><div class="col-12"><q-input v-model="form.actividad" outlined label="Actividad" :disable="!canManage"/></div><div class="col-12 col-sm-6"><q-input v-model="form.telefono" outlined label="Teléfono" :disable="!canManage"/></div><div class="col-12 col-sm-6"><q-input v-model="form.whatsapp" outlined label="WhatsApp" :disable="!canManage"/></div><div class="col-12 col-sm-6"><q-input v-model="form.ciudad" outlined label="Ciudad" :disable="!canManage"/></div><div class="col-12 col-sm-6"><q-input v-model="form.moneda" outlined label="Moneda" :disable="!canManage"/></div><div class="col-12"><q-input v-model="form.direccion" outlined label="Dirección" :disable="!canManage"/></div><div class="col-12"><q-input v-model="form.zona_horaria" outlined label="Zona horaria" :disable="!canManage"/></div></div></q-card-section><q-card-actions v-if="canManage" align="right" class="q-pa-md"><q-btn color="primary" unelevated no-caps label="Guardar cambios" :loading="saving" @click="save"/></q-card-actions></q-card></div>
<div class="col-12 col-lg-5"><q-card flat class="viti-card"><q-card-section><div class="text-h6 text-weight-bold">Plan VITI</div><div class="text-caption text-grey-6">Los límites se aplican solo cuando el plan los define.</div></q-card-section><q-separator/><q-card-section><div class="text-h5 text-weight-bold">{{info?.empresa?.plan_viti?.nombre||info?.empresa?.planViti?.nombre||'Personalizado'}}</div><div class="q-mt-md text-body2">Usuarios: {{info?.empresa?.plan_viti?.max_usuarios||info?.empresa?.planViti?.max_usuarios||'Sin límite'}}<br>Aplicaciones: {{info?.empresa?.plan_viti?.max_aplicaciones||info?.empresa?.planViti?.max_aplicaciones||'Sin límite'}}</div></q-card-section></q-card></div></div>
<q-card v-if="canManage && !loading" flat class="viti-card q-mt-lg"><q-card-section class="row items-center"><div><div class="text-h6 text-weight-bold">Equipo del negocio</div><div class="text-caption text-grey-6">Cada persona usa su propia cuenta. Nada de contraseña comunitaria, ese deporte ya sufrió bastante.</div></div><q-space/><q-btn color="primary" unelevated no-caps icon="person_add" label="Agregar usuario" @click="newMember"/></q-card-section><q-separator/><q-table flat :rows="team" :columns="columns" row-key="id"><template #body-cell-persona="p"><q-td :props="p"><div class="text-weight-bold">{{p.row.nombre}} {{p.row.apellido}}</div><div class="text-caption text-grey-6">{{p.row.usuario}}</div></q-td></template><template #body-cell-rol="p"><q-td :props="p"><q-badge outline color="primary">{{pretty(p.row.rol_negocio)}}</q-badge></q-td></template><template #body-cell-estado="p"><q-td :props="p"><q-badge :color="p.row.activo?'positive':'grey'">{{p.row.activo?'Activo':'Sin acceso'}}</q-badge></q-td></template><template #body-cell-acciones="p"><q-td :props="p"><q-btn flat round dense icon="more_vert"><q-menu><q-list><q-item clickable v-close-popup @click="editMember(p.row)"><q-item-section avatar><q-icon name="edit"/></q-item-section><q-item-section>Editar acceso</q-item-section></q-item><q-item clickable v-close-popup @click="removeMember(p.row)"><q-item-section avatar><q-icon name="person_remove" color="negative"/></q-item-section><q-item-section>Quitar acceso</q-item-section></q-item></q-list></q-menu></q-btn></q-td></template></q-table></q-card>
<q-dialog v-model="dialog"><q-card style="width:560px;max-width:94vw"><q-card-section><div class="text-h6 text-weight-bold">{{editing?'Editar acceso':'Agregar usuario'}}</div></q-card-section><q-separator/><q-card-section><div v-if="!editing" class="row q-col-gutter-md"><div class="col-6"><q-input v-model="member.nombre" outlined label="Nombre"/></div><div class="col-6"><q-input v-model="member.apellido" outlined label="Apellido"/></div><div class="col-6"><q-input v-model="member.usuario" outlined label="Usuario"/></div><div class="col-6"><q-input v-model="member.telefono" outlined label="Teléfono"/></div></div><q-select v-model="member.rol_negocio" class="q-mt-md" outlined :options="roles" emit-value map-options label="Rol"/><q-input v-model="member.password" class="q-mt-md" outlined type="password" :label="editing?'Nueva contraseña (opcional)':'Contraseña'"/><q-toggle v-if="editing" v-model="member.activo" class="q-mt-md" label="Acceso activo"/></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Cancelar" v-close-popup/><q-btn color="primary" unelevated no-caps label="Guardar" @click="saveMember"/></q-card-actions></q-card></q-dialog></q-page></template>
