<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { useQuasar } from 'quasar'
import { api } from '../boot/axios'
import { useTenantStore } from '../stores/tenant'
import PageHeader from '../components/PageHeader.vue'

const $q = useQuasar()
const tenant = useTenantStore()
const loading = ref(true)
const saving = ref(false)
const info = ref(null)
const team = ref([])
const dialog = ref(false)
const editing = ref(null)
const form = reactive({ nombre_comercial:'',razon_social:'',actividad:'',telefono:'',whatsapp:'',ciudad:'',direccion:'',moneda:'BOB',zona_horaria:'America/La_Paz' })
const member = reactive({ nombre:'',apellido:'',usuario:'',documento:'',telefono:'',password:'',password_confirmation:'',rol_negocio:'empleado',permisos:['inicio','agenda','ordenes'],activo:true })
const canManage = computed(() => !!info.value?.puede_administrar)
const activePlan = computed(() => info.value?.empresa?.plan_viti || info.value?.empresa?.planViti || null)
const moduleNames = {inicio:'Inicio',agenda:'Agenda',ordenes:'Órdenes',clientes:'Clientes',equipos:'Equipos',tecnicos:'Técnicos',inventario:'Inventario',pagos:'Pagos',garantias:'Garantías',historial:'Historial y reportes',buzon:'Mensajes'}
const roles = [{label:'Propietario',value:'propietario'},{label:'Administrador',value:'administrador'},{label:'Empleado',value:'empleado'}]
const moduleOptions=computed(()=>(activePlan.value?.modulos||Object.keys(moduleNames)).map(value=>({label:moduleNames[value]||pretty(value),value})))
const columns=[{name:'persona',label:'Usuario',field:'nombre',align:'left'},{name:'rol',label:'Rol',field:'rol_negocio',align:'left'},{name:'permisos',label:'Acceso',field:'permisos',align:'left'},{name:'estado',label:'Estado',field:'activo',align:'left'},{name:'acciones',label:'',field:'id',align:'right'}]

function pretty(v){return String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
async function load(){loading.value=true;try{if(!tenant.loaded) await tenant.load(); const {data}=await api.get('/mi/negocio');info.value=data.data;Object.assign(form,data.data.empresa||{});if(data.data.puede_administrar){team.value=(await api.get('/mi/negocio/equipo')).data.data||[]}else team.value=[]}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo cargar el negocio.'})}finally{loading.value=false}}
async function save(){saving.value=true;try{await api.put('/mi/negocio',form);$q.notify({type:'positive',message:'Negocio actualizado.'});await tenant.load();await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo guardar.'})}finally{saving.value=false}}
async function uploadLogo(event){const file=event.target.files?.[0];if(!file)return;const body=new FormData();body.append('logo',file);try{await api.post('/mi/negocio/logo',body,{headers:{'Content-Type':'multipart/form-data'}});$q.notify({type:'positive',message:'Logo actualizado.'});await tenant.load();await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo subir el logo.'})}finally{event.target.value=''}}
function newMember(){editing.value=null;const modules=activePlan.value?.modulos||Object.keys(moduleNames);Object.assign(member,{nombre:'',apellido:'',usuario:'',documento:'',telefono:'',password:'',password_confirmation:'',rol_negocio:'empleado',permisos:['inicio','agenda','ordenes'].filter(x=>modules.includes(x)),activo:true});dialog.value=true}
function editMember(row){editing.value=row;Object.assign(member,{nombre:row.nombre,apellido:row.apellido||'',usuario:row.usuario,documento:row.documento||'',telefono:row.telefono||'',password:'',password_confirmation:'',rol_negocio:row.rol_negocio,permisos:row.permisos||[],activo:row.activo});dialog.value=true}
async function saveMember(){try{const payload={...member,permisos:member.rol_negocio==='empleado'?member.permisos:null};if(editing.value)await api.put(`/mi/negocio/equipo/${editing.value.id}`,{rol_negocio:payload.rol_negocio,permisos:payload.permisos,activo:payload.activo,password:payload.password||null,password_confirmation:payload.password_confirmation||null});else await api.post('/mi/negocio/equipo',payload);dialog.value=false;$q.notify({type:'positive',message:editing.value?'Acceso actualizado.':'Usuario agregado.'});await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||Object.values(e.response?.data?.errors||{}).flat()[0]||'No se pudo guardar el usuario.'})}}
async function removeMember(row){if(!confirm(`¿Quitar el acceso de ${row.nombre}?`))return;try{await api.delete(`/mi/negocio/equipo/${row.id}`);await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo quitar el acceso.'})}}
function tenantChanged(){load()}
onMounted(()=>{load();window.addEventListener('viti-tenant-changed',tenantChanged)})
onBeforeUnmount(()=>window.removeEventListener('viti-tenant-changed',tenantChanged))
</script>

<template><q-page class="viti-page"><PageHeader eyebrow="Mi espacio VITI" title="Mi negocio" subtitle="Configura los datos del negocio y controla quién puede trabajar en él."/><q-inner-loading :showing="loading"/>
<div v-if="!loading" class="row q-col-gutter-lg"><div class="col-12 col-lg-7"><q-card flat class="viti-card"><q-card-section class="row items-center"><div><div class="text-h6 text-weight-bold">Datos del negocio</div><div class="text-caption text-grey-6">Rol actual: {{pretty(info?.rol)}}</div></div><q-space/><label v-if="canManage" class="cursor-pointer"><q-btn outline color="primary" no-caps icon="image" label="Cambiar logo"/><input hidden type="file" accept="image/png,image/jpeg,image/webp" @change="uploadLogo"/></label></q-card-section><q-separator/><q-card-section><div class="row q-col-gutter-md"><div class="col-12 col-sm-6"><q-input v-model="form.nombre_comercial" outlined label="Nombre comercial" :disable="!canManage"/></div><div class="col-12 col-sm-6"><q-input v-model="form.razon_social" outlined label="Razón social" :disable="!canManage"/></div><div class="col-12"><q-input v-model="form.actividad" outlined label="Actividad" :disable="!canManage"/></div><div class="col-12 col-sm-6"><q-input v-model="form.telefono" outlined label="Teléfono" :disable="!canManage"/></div><div class="col-12 col-sm-6"><q-input v-model="form.whatsapp" outlined label="WhatsApp" :disable="!canManage"/></div><div class="col-12 col-sm-6"><q-input v-model="form.ciudad" outlined label="Ciudad" :disable="!canManage"/></div><div class="col-12 col-sm-6"><q-input v-model="form.moneda" outlined label="Moneda" :disable="!canManage"/></div><div class="col-12"><q-input v-model="form.direccion" outlined label="Dirección" :disable="!canManage"/></div><div class="col-12"><q-input v-model="form.zona_horaria" outlined label="Zona horaria" :disable="!canManage"/></div></div></q-card-section><q-card-actions v-if="canManage" align="right" class="q-pa-md"><q-btn color="primary" unelevated no-caps label="Guardar cambios" :loading="saving" @click="save"/></q-card-actions></q-card></div>
<div class="col-12 col-lg-5"><q-card flat class="viti-card"><q-card-section><div class="text-h6 text-weight-bold">Plan VITI</div><div class="text-caption text-grey-6">Módulos y límites activos para este negocio.</div></q-card-section><q-separator/><q-card-section><div class="text-h5 text-weight-bold">{{activePlan?.nombre||'Personalizado'}}</div><div v-if="activePlan?.precio_proyecto" class="text-subtitle1 text-primary text-weight-bold q-mt-xs">{{Number(activePlan.precio_proyecto).toFixed(0)}} Bs</div><div class="q-mt-md text-body2">Usuarios: {{activePlan?.max_usuarios||'Sin límite'}}<br>Aplicaciones: {{activePlan?.max_aplicaciones||'Sin límite'}}</div><div v-if="activePlan?.modulos?.length" class="row q-gutter-xs q-mt-md"><q-chip v-for="module in activePlan.modulos" :key="module" dense color="blue-1" text-color="primary">{{moduleNames[module]||pretty(module)}}</q-chip></div></q-card-section></q-card></div></div>
<q-card v-if="canManage && !loading" flat class="viti-card q-mt-lg"><q-card-section class="row items-center"><div><div class="text-h6 text-weight-bold">Equipo del negocio</div><div class="text-caption text-grey-6">Cada persona usa su propia cuenta y solo ve los módulos que necesita.</div></div><q-space/><q-btn color="primary" unelevated no-caps icon="person_add" label="Agregar usuario" @click="newMember"/></q-card-section><q-separator/><q-table flat :rows="team" :columns="columns" row-key="id"><template #body-cell-persona="p"><q-td :props="p"><div class="text-weight-bold">{{p.row.nombre}} {{p.row.apellido}}</div><div class="text-caption text-grey-6">@{{p.row.usuario}} · CI {{p.row.documento||'sin registrar'}}</div></q-td></template><template #body-cell-rol="p"><q-td :props="p"><q-badge outline color="primary">{{pretty(p.row.rol_negocio)}}</q-badge></q-td></template><template #body-cell-permisos="p"><q-td :props="p"><span v-if="p.row.rol_negocio!=='empleado'" class="text-caption text-grey-6">Todos los módulos</span><div v-else class="row q-gutter-xs"><q-chip v-for="permission in p.row.permisos" :key="permission" dense size="sm">{{moduleNames[permission]||pretty(permission)}}</q-chip></div></q-td></template><template #body-cell-estado="p"><q-td :props="p"><q-badge :color="p.row.activo?'positive':'grey'">{{p.row.activo?'Activo':'Sin acceso'}}</q-badge></q-td></template><template #body-cell-acciones="p"><q-td :props="p"><q-btn flat round dense icon="more_vert"><q-menu><q-list><q-item clickable v-close-popup @click="editMember(p.row)"><q-item-section avatar><q-icon name="edit"/></q-item-section><q-item-section>Editar acceso</q-item-section></q-item><q-item clickable v-close-popup @click="removeMember(p.row)"><q-item-section avatar><q-icon name="person_remove" color="negative"/></q-item-section><q-item-section>Quitar acceso</q-item-section></q-item></q-list></q-menu></q-btn></q-td></template></q-table></q-card>
<q-dialog v-model="dialog"><q-card style="width:620px;max-width:94vw"><q-card-section><div class="text-h6 text-weight-bold">{{editing?'Editar acceso':'Agregar usuario'}}</div><div class="text-caption text-grey-6">La cuenta queda identificada por su usuario y documento.</div></q-card-section><q-separator/><q-card-section><div v-if="!editing" class="row q-col-gutter-md"><div class="col-12 col-sm-6"><q-input v-model="member.nombre" outlined label="Nombre *"/></div><div class="col-12 col-sm-6"><q-input v-model="member.apellido" outlined label="Apellido"/></div><div class="col-12 col-sm-6"><q-input v-model="member.usuario" outlined label="Usuario *" prefix="@"/></div><div class="col-12 col-sm-6"><q-input v-model="member.documento" outlined label="CI *" inputmode="numeric"/></div><div class="col-12"><q-input v-model="member.telefono" outlined label="Teléfono" inputmode="tel"/></div></div><q-select v-model="member.rol_negocio" class="q-mt-md" outlined :options="roles" emit-value map-options label="Rol"/><q-select v-if="member.rol_negocio==='empleado'" v-model="member.permisos" class="q-mt-md" outlined multiple use-chips emit-value map-options :options="moduleOptions" label="Módulos permitidos *" hint="El menú y la API respetarán esta selección."/><div class="row q-col-gutter-md q-mt-xs"><div class="col-12 col-sm-6"><q-input v-model="member.password" outlined type="password" :label="editing?'Nueva contraseña (opcional)':'Contraseña *'" hint="Mínimo 8 caracteres, letras y números."/></div><div class="col-12 col-sm-6"><q-input v-model="member.password_confirmation" outlined type="password" label="Confirmar contraseña"/></div></div><q-toggle v-if="editing" v-model="member.activo" class="q-mt-md" label="Acceso activo"/></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Cancelar" v-close-popup/><q-btn color="primary" unelevated no-caps label="Guardar" @click="saveMember"/></q-card-actions></q-card></q-dialog></q-page></template>
