<script setup>
import { onMounted, ref } from 'vue'
import { api } from '../boot/axios'
import PageHeader from '../components/PageHeader.vue'
const data=ref({resumen:{},solicitudes_recientes:[],proyectos_recientes:[]}),loading=ref(true)
onMounted(async()=>{try{data.value=(await api.get('/dashboard')).data}finally{loading.value=false}})
const cards=[['clientes','Clientes','people','#1976d2','/clientes'],['empresas','Empresas registradas','business','#43a047','/clientes'],['solicitudes_activas','Solicitudes activas','assignment','#fb8c00','/solicitudes'],['proyectos_activos','Proyectos activos','account_tree','#8e24aa','/proyectos'],['aplicaciones','Aplicaciones','apps','#00897b','/aplicaciones'],['mantenimientos_abiertos','Soporte abierto','support_agent','#e53935','/mantenimientos']]
</script>
<template><q-page class="viti-page"><PageHeader eyebrow="Panel principal" title="VITI está listo para comenzar" subtitle="La plataforma inicia limpia: registra tu primer cliente y construye su solución paso a paso."><q-btn color="primary" unelevated icon="person_add" label="Registrar cliente" no-caps to="/clientes?new=1"/></PageHeader>
<div class="row q-col-gutter-md"><div v-for="card in cards" :key="card[0]" class="col-12 col-sm-6 col-lg-4"><q-card flat class="viti-card q-pa-lg cursor-pointer" @click="$router.push(card[4])"><div class="row items-center"><q-avatar :style="{background:card[3]+'18',color:card[3]}" :icon="card[2]" size="52px"/><q-space/><q-icon name="arrow_forward" color="grey-5"/></div><div class="stat-value q-mt-md">{{data.resumen[card[0]]||0}}</div><div class="stat-label">{{card[1]}}</div></q-card></div></div>
<div class="row q-col-gutter-lg q-mt-sm"><div class="col-12 col-lg-6"><q-card flat class="viti-card"><q-card-section><div class="text-h6 text-weight-bold">Solicitudes recientes</div><div class="text-caption text-grey-6">Cuestionarios y requerimientos de clientes.</div></q-card-section><q-separator/><q-list v-if="data.solicitudes_recientes.length"><q-item v-for="item in data.solicitudes_recientes" :key="item.id" clickable :to="`/solicitudes/${item.id}`"><q-item-section avatar><q-avatar color="orange-1" text-color="orange-8" icon="description"/></q-item-section><q-item-section><q-item-label>{{item.titulo}}</q-item-label><q-item-label caption>{{item.empresa?.nombre_comercial}} · {{item.cliente?.nombre}}</q-item-label></q-item-section><q-item-section side><q-badge outline color="primary">{{item.estado}}</q-badge></q-item-section></q-item></q-list><div v-else class="empty-state"><q-icon name="assignment" size="46px"/><div class="q-mt-sm">Todavía no hay solicitudes.</div></div></q-card></div>
<div class="col-12 col-lg-6"><q-card flat class="viti-card"><q-card-section><div class="text-h6 text-weight-bold">Proyectos recientes</div><div class="text-caption text-grey-6">Del levantamiento a la entrega final.</div></q-card-section><q-separator/><q-list v-if="data.proyectos_recientes.length"><q-item v-for="item in data.proyectos_recientes" :key="item.id" clickable :to="`/proyectos/${item.id}`"><q-item-section avatar><q-avatar color="purple-1" text-color="purple-8" icon="account_tree"/></q-item-section><q-item-section><q-item-label>{{item.nombre}}</q-item-label><q-item-label caption>{{item.empresa?.nombre_comercial}} · {{item.fase}}</q-item-label></q-item-section><q-item-section side>{{item.progreso}}%</q-item-section></q-item></q-list><div v-else class="empty-state"><q-icon name="rocket_launch" size="46px"/><div class="q-mt-sm">Los proyectos aparecerán aquí cuando apruebes una solicitud.</div></div></q-card></div></div></q-page></template>
