<script setup>
import { onMounted, ref } from 'vue'
import { api } from '../boot/axios'
import PageHeader from '../components/PageHeader.vue'
const data=ref({resumen:{},solicitudes_recientes:[],proyectos_recientes:[],requieren_atencion:[]});const loading=ref(true)
const cards=[{key:'negocios_activos',label:'Negocios activos',icon:'business',color:'blue',to:'/clientes'},{key:'aplicaciones_activas',label:'Apps activas',icon:'apps',color:'teal',to:'/saas'},{key:'suscripciones_activas',label:'Suscripciones activas',icon:'autorenew',color:'green',to:'/pagos'},{key:'pagos_vencidos',label:'Pagos con atención',icon:'schedule',color:'orange',to:'/pagos'}]
function pretty(v){return String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
onMounted(async()=>{try{data.value=(await api.get('/dashboard')).data}finally{loading.value=false}})
</script>
<template><q-page class="viti-page"><q-inner-loading :showing="loading"/><PageHeader eyebrow="SaaS" title="Panel VITI" subtitle="La plataforma en una mirada: negocios, aplicaciones, suscripciones y lo que requiere atención."><q-btn color="primary" unelevated icon="person_add" label="Registrar cliente" no-caps to="/clientes?new=1"/></PageHeader><div class="row q-col-gutter-md"><div v-for="card in cards" :key="card.key" class="col-12 col-sm-6 col-xl-3"><q-card flat class="viti-card action-card cursor-pointer" @click="$router.push(card.to)"><q-card-section><div class="row items-center no-wrap"><q-avatar :color="`${card.color}-1`" :text-color="`${card.color}-8`" :icon="card.icon" size="50px"/><q-space/><q-icon name="arrow_forward" color="grey-5"/></div><div class="stat-value q-mt-md">{{data.resumen[card.key]||0}}</div><div class="stat-label">{{card.label}}</div></q-card-section></q-card></div></div>
<div class="row q-col-gutter-lg q-mt-sm"><div class="col-12 col-lg-6"><q-card flat class="viti-card full-height"><q-card-section class="row items-center"><div><div class="text-h6 text-weight-bold">Necesitan atención</div><div class="text-caption text-grey-6">Entregas, vencimientos y suspensiones detectadas por VITI.</div></div><q-space/><q-btn flat dense no-caps color="primary" label="Centro SaaS" to="/saas"/></q-card-section><q-separator/><q-list v-if="data.requieren_atencion?.length" separator><q-item v-for="row in data.requieren_atencion" :key="row.app.id" clickable to="/saas"><q-item-section avatar><q-avatar color="orange-1" text-color="orange-9" :icon="row.ciclo.estado==='lista_entrega'?'key':row.ciclo.estado==='suspendida'?'block':'schedule'"/></q-item-section><q-item-section><q-item-label class="text-weight-bold">{{row.app.nombre}}</q-item-label><q-item-label caption>{{row.app.empresa?.nombre_comercial}} · {{row.ciclo.mensaje}}</q-item-label></q-item-section><q-item-section side><q-badge :color="row.ciclo.estado==='suspendida'?'negative':'orange'">{{pretty(row.ciclo.estado)}}</q-badge></q-item-section></q-item></q-list><div v-else class="empty-state"><q-icon name="task_alt" size="46px"/><div class="q-mt-sm">No hay incidencias SaaS pendientes.</div></div></q-card></div>
<div class="col-12 col-lg-6"><q-card flat class="viti-card"><q-card-section><div class="text-h6 text-weight-bold">Operación de hoy</div><div class="text-caption text-grey-6">Lo que todavía requiere trabajo humano, ese componente que insiste en seguir siendo necesario.</div></q-card-section><q-separator/><q-list><q-item clickable to="/solicitudes"><q-item-section avatar><q-avatar color="orange-1" text-color="orange-8" icon="assignment"/></q-item-section><q-item-section>Solicitudes activas</q-item-section><q-item-section side><strong>{{data.resumen.solicitudes_activas||0}}</strong></q-item-section></q-item><q-item clickable to="/proyectos"><q-item-section avatar><q-avatar color="purple-1" text-color="purple-8" icon="account_tree"/></q-item-section><q-item-section>Proyectos activos</q-item-section><q-item-section side><strong>{{data.resumen.proyectos_activos||0}}</strong></q-item-section></q-item><q-item clickable to="/mantenimientos"><q-item-section avatar><q-avatar color="red-1" text-color="red-8" icon="support_agent"/></q-item-section><q-item-section>Soportes abiertos</q-item-section><q-item-section side><strong>{{data.resumen.mantenimientos_abiertos||0}}</strong></q-item-section></q-item><q-item clickable to="/aplicaciones"><q-item-section avatar><q-avatar color="teal-1" text-color="teal-8" icon="key"/></q-item-section><q-item-section>Pendientes de entrega</q-item-section><q-item-section side><strong>{{data.resumen.aplicaciones_pendientes_entrega||0}}</strong></q-item-section></q-item></q-list></q-card></div></div></q-page></template>
<style scoped>.action-card{height:100%;transition:transform .15s ease,box-shadow .15s ease}.action-card:hover{transform:translateY(-2px);box-shadow:0 10px 24px rgba(12,35,64,.08)}</style>
