<script setup>
import { reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useQuasar } from 'quasar'
import { useAuthStore } from '../stores/auth'
const auth=useAuthStore(),router=useRouter(),route=useRoute(),$q=useQuasar(),show=ref(false),form=reactive({acceso:'',password:''})
async function submit(){try{await auth.loginElectrofrioCustomer(form);const redirect=String(route.query.redirect||'');router.replace(redirect.startsWith('/portal/electrofrio')?redirect:'/portal/electrofrio/inicio')}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo iniciar sesión.'})}}
</script>
<template><q-page class="customer-login flex flex-center"><q-card flat class="login-panel"><q-card-section class="text-center"><q-avatar size="72px" color="primary" text-color="white" icon="ac_unit"/><div class="text-h4 text-weight-bold q-mt-md">Electrofrío</div><div class="text-body2 text-grey-6">Consulta tus visitas, equipos y mensajes del servicio.</div></q-card-section><q-card-section><q-form @submit="submit"><q-input v-model="form.acceso" outlined label="Usuario, teléfono o CI" :rules="[v=>!!v||'Dato obligatorio']"><template #prepend><q-icon name="badge"/></template></q-input><q-input v-model="form.password" outlined class="q-mt-sm" :type="show?'text':'password'" label="Contraseña" :rules="[v=>!!v||'Dato obligatorio']"><template #append><q-icon :name="show?'visibility_off':'visibility'" class="cursor-pointer" @click="show=!show"/></template></q-input><q-btn type="submit" color="primary" unelevated no-caps size="lg" class="full-width q-mt-md" label="Ingresar a mi servicio" :loading="auth.loading"/></q-form></q-card-section><q-card-section class="text-caption text-grey-6 text-center">Tu acceso lo habilita directamente la empresa que te brinda el servicio.</q-card-section></q-card></q-page></template>
<style scoped>.customer-login{min-height:100vh;padding:20px;background:radial-gradient(circle at 80% 10%,rgba(18,184,200,.2),transparent 32%),linear-gradient(145deg,#eaf5fb,#f8fbfd)}.login-panel{width:min(480px,100%);padding:24px;border-radius:24px;box-shadow:0 24px 70px rgba(11,95,122,.18)}.body--dark .customer-login{background:#071827}.body--dark .login-panel{background:#102a43;color:#f4fbff}@media(max-width:600px){.customer-login{padding:0;align-items:stretch}.login-panel{width:100%;min-height:100vh;border-radius:0;padding:34px 16px}}</style>
