<script setup>
import { onMounted, reactive, ref, watch } from 'vue'
import { useQuasar } from 'quasar'
import { api } from '../boot/axios'
import PageHeader from '../components/PageHeader.vue'
import RowActionsMenu from '../components/RowActionsMenu.vue'

const $q=useQuasar()
const rows=ref([]),clients=ref([]),users=ref([]),loading=ref(false),saving=ref(false),dialog=ref(false),editing=ref(null),search=ref(''),logoFile=ref(null)
const empty=()=>({cliente_id:null,usuario_id:null,nombre_comercial:'',razon_social:'',actividad:'',telefono:'',whatsapp:'',ciudad:'',direccion:'',observaciones:'',estado:'prospecto'})
const form=reactive(empty())
const columns=[{name:'actions',label:'',field:'actions',align:'left'},{name:'codigo',label:'Código',field:'codigo',align:'left'},{name:'nombre',label:'Empresa',field:'nombre_comercial',align:'left',sortable:true},{name:'cliente',label:'Cliente',field:r=>r.cliente?.nombre||'Sin cliente',align:'left'},{name:'propietario',label:'Propietario',field:r=>owner(r)?.nombre_completo||'Sin propietario',align:'left'},{name:'telefono',label:'Teléfono',field:'telefono',align:'left'},{name:'actividad',label:'Actividad',field:'actividad',align:'left'},{name:'solicitudes',label:'Solicitudes',field:'solicitudes_count',align:'center'},{name:'proyectos',label:'Proyectos',field:'proyectos_count',align:'center'},{name:'estado',label:'Estado',field:'estado',align:'left'}]
function owner(row){const u=(row.usuarios||[]).find(item=>item?.pivot?.rol_negocio==='propietario'&&item?.pivot?.activo!==false);if(!u)return null;return {...u,nombre_completo:[u.nombre,u.apellido].filter(Boolean).join(' ')||u.usuario}}
function userLabel(user){const name=[user.nombre,user.apellido].filter(Boolean).join(' ')||user.usuario;return `${name} · @${user.usuario}`}
async function load(){loading.value=true;try{const [e,c,u]=await Promise.all([api.get('/empresas',{params:{buscar:search.value,per_page:100}}),api.get('/clientes',{params:{per_page:100}}),api.get('/usuarios',{params:{per_page:100}})]);rows.value=e.data.data||[];clients.value=c.data.data||[];users.value=(u.data.data||[]).filter(user=>user.estado==='activo'&&user.rol==='cliente'&&user.cliente_id)}finally{loading.value=false}}
function open(row=null){editing.value=row;Object.assign(form,empty(),row||{});form.usuario_id=owner(row)?.id||null;dialog.value=true;logoFile.value=null}
async function save(){if(saving.value||!form.nombre_comercial.trim())return;saving.value=true;try{let id;const payload={...form};delete payload.usuario_id;if(editing.value){id=editing.value.id;await api.put(`/empresas/${id}`,{...payload,usuario_id:form.usuario_id})}else{const created=(await api.post('/empresas',payload)).data.data;id=created.id;if(form.usuario_id)await api.put(`/empresas/${id}`,{...payload,usuario_id:form.usuario_id})}if(logoFile.value){const fd=new FormData();fd.append('logo',logoFile.value);await api.post(`/empresas/${id}/logo`,fd)}$q.notify({type:'positive',message:editing.value?'Empresa actualizada.':'Empresa registrada.'});dialog.value=false;await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo guardar.'})}finally{saving.value=false}}
function remove(row){$q.dialog({title:'Eliminar empresa',message:`¿Eliminar ${row.nombre_comercial}?`,cancel:true}).onOk(async()=>{try{await api.delete(`/empresas/${row.id}`);await load();$q.notify({type:'positive',message:'Empresa enviada a papelera.'})}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se puede eliminar.'})}})}
onMounted(load);watch(search,()=>{clearTimeout(window.__vitiCompanySearch);window.__vitiCompanySearch=setTimeout(load,350)})
</script>
<template><q-page class="viti-page"><PageHeader eyebrow="Relaciones" title="Empresas" subtitle="Negocios registrados en VITI, sus clientes y su propietario operativo."><q-btn color="primary" unelevated icon="add_business" label="Nueva empresa" no-caps @click="open()"/></PageHeader><q-table flat class="viti-table" :rows="rows" :columns="columns" row-key="id" :loading="loading" :pagination="{rowsPerPage:20,sortBy:'id',descending:true}"><template #top><q-input v-model="search" outlined dense placeholder="Buscar empresa" style="min-width:300px"><template #prepend><q-icon name="search"/></template></q-input></template><template #body-cell-actions="p"><q-td :props="p"><RowActionsMenu @open="open(p.row)" @edit="open(p.row)" @delete="remove(p.row)"/></q-td></template><template #body-cell-propietario="p"><q-td :props="p"><q-badge v-if="owner(p.row)" outline color="primary">{{owner(p.row).nombre_completo}}</q-badge><q-badge v-else outline color="orange">Sin propietario</q-badge></q-td></template><template #body-cell-cliente="p"><q-td :props="p"><q-badge v-if="p.row.cliente" outline color="secondary">{{p.row.cliente.nombre}}</q-badge><q-badge v-else outline color="grey-7">Sin cliente</q-badge></q-td></template><template #body-cell-estado="p"><q-td :props="p"><q-badge outline color="primary">{{p.value}}</q-badge></q-td></template><template #no-data><div class="empty-state full-width"><q-icon name="business" size="52px"/><div class="text-h6 q-mt-sm">No hay empresas registradas</div><div>Una empresa puede existir sin cliente o propietario mientras VITI completa su asignación.</div></div></template></q-table>
<q-dialog v-model="dialog"><q-card style="width:900px;max-width:95vw"><q-card-section><div class="section-label">{{editing?'Editar':'Nueva'}} empresa</div><div class="text-h5 text-weight-bold">{{editing?'Actualizar empresa':'Registrar empresa'}}</div></q-card-section><q-separator/><q-card-section><div class="row q-col-gutter-md"><div class="col-12 col-md-6"><q-select v-model="form.cliente_id" outlined emit-value map-options :options="clients.map(c=>({label:`${c.nombre} · ${c.telefono}`,value:c.id}))" label="Cliente relacionado" clearable/><div class="text-caption text-grey-7 q-mt-xs">Puede quedar vacío. Electro Frío está precisamente en ese estado.</div></div><div class="col-12 col-md-6"><q-select v-model="form.usuario_id" outlined emit-value map-options clearable :options="users.map(u=>({label:userLabel(u),value:u.id}))" label="Propietario del negocio"/><div class="text-caption text-grey-7 q-mt-xs">Solo aparecen cuentas de cliente activas. Vacío = sin propietario.</div></div><div class="col-12 col-sm-7"><q-input v-model="form.nombre_comercial" outlined label="Nombre comercial *"/></div><div class="col-12 col-sm-5"><q-input v-model="form.razon_social" outlined label="Razón social"/></div><div class="col-12"><q-input v-model="form.actividad" outlined label="Actividad o rubro"/></div><div class="col-12 col-sm-4"><q-input v-model="form.telefono" outlined label="Teléfono"/></div><div class="col-12 col-sm-4"><q-input v-model="form.whatsapp" outlined label="WhatsApp"/></div><div class="col-12 col-sm-4"><q-input v-model="form.ciudad" outlined label="Ciudad"/></div><div class="col-12"><q-input v-model="form.direccion" outlined label="Dirección"/></div><div class="col-12"><q-file v-model="logoFile" outlined accept="image/*" label="Logotipo de la empresa (opcional)" clearable/></div><div class="col-12"><q-input v-model="form.observaciones" outlined type="textarea" label="Observaciones"/></div><div class="col-12 col-sm-4"><q-select v-model="form.estado" outlined :options="['prospecto','levantamiento','desarrollo','activo','inactivo']" label="Estado"/></div></div></q-card-section><q-card-actions align="right"><q-btn flat label="Cancelar" v-close-popup :disable="saving"/><q-btn color="primary" unelevated :loading="saving" :label="editing?'Guardar cambios':'Registrar empresa'" no-caps @click="save"/></q-card-actions></q-card></q-dialog></q-page></template>
