<script setup>
import { onMounted, reactive, ref, watch } from 'vue'
import { useQuasar } from 'quasar'
import { api } from '../boot/axios'
import PageHeader from '../components/PageHeader.vue'
import RowActionsMenu from '../components/RowActionsMenu.vue'
const $q=useQuasar(),rows=ref([]),clients=ref([]),loading=ref(false),dialog=ref(false),editing=ref(null),search=ref(''),logoFile=ref(null)
const empty=()=>({cliente_id:null,nombre_comercial:'',razon_social:'',actividad:'',telefono:'',whatsapp:'',ciudad:'',direccion:'',observaciones:'',estado:'prospecto'});const form=reactive(empty())
const columns=[{name:'actions',label:'',field:'actions',align:'left'},{name:'codigo',label:'Código',field:'codigo',align:'left'},{name:'nombre',label:'Empresa',field:'nombre_comercial',align:'left',sortable:true},{name:'responsable',label:'Responsable',field:r=>r.cliente?.nombre||'Sin asignar',align:'left'},{name:'telefono',label:'Teléfono',field:'telefono',align:'left'},{name:'actividad',label:'Actividad',field:'actividad',align:'left'},{name:'solicitudes',label:'Solicitudes',field:'solicitudes_count',align:'center'},{name:'proyectos',label:'Proyectos',field:'proyectos_count',align:'center'},{name:'estado',label:'Estado',field:'estado',align:'left'}]
async function load(){loading.value=true;try{const [e,c]=await Promise.all([api.get('/empresas',{params:{buscar:search.value,per_page:100}}),api.get('/clientes',{params:{per_page:100}})]);rows.value=e.data.data;clients.value=c.data.data}finally{loading.value=false}}
function open(row=null){editing.value=row;Object.assign(form,empty(),row||{});dialog.value=true;logoFile.value=null}
async function save(){try{let id;if(editing.value){await api.put(`/empresas/${editing.value.id}`,form);id=editing.value.id}else{id=(await api.post('/empresas',form)).data.data.id}if(logoFile.value){const fd=new FormData();fd.append('logo',logoFile.value);await api.post(`/empresas/${id}/logo`,fd)}$q.notify({type:'positive',message:editing.value?'Empresa actualizada.':'Empresa registrada.'});dialog.value=false;load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo guardar.'})}}
function remove(row){$q.dialog({title:'Eliminar empresa',message:`¿Eliminar ${row.nombre_comercial}?`,cancel:true}).onOk(async()=>{try{await api.delete(`/empresas/${row.id}`);load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se puede eliminar.'})}})}
onMounted(load);watch(search,()=>{clearTimeout(window.__vitiCompanySearch);window.__vitiCompanySearch=setTimeout(load,350)})
</script>
<template><q-page class="viti-page"><PageHeader eyebrow="Relaciones" title="Empresas" subtitle="Negocios de tus clientes para los que diseñarás e integrarás un sistema."><q-btn color="primary" unelevated icon="add_business" label="Nueva empresa" no-caps @click="open()"/></PageHeader><q-table flat class="viti-table" :rows="rows" :columns="columns" row-key="id" :loading="loading" :pagination="{rowsPerPage:20,sortBy:'id',descending:true}"><template #top><q-input v-model="search" outlined dense placeholder="Buscar empresa" style="min-width:300px"><template #prepend><q-icon name="search"/></template></q-input></template><template #body-cell-actions="p"><q-td :props="p"><RowActionsMenu @open="open(p.row)" @edit="open(p.row)" @delete="remove(p.row)"/></q-td></template><template #body-cell-estado="p"><q-td :props="p"><q-badge outline color="primary">{{p.value}}</q-badge></q-td></template><template #no-data><div class="empty-state full-width"><q-icon name="business" size="52px"/><div class="text-h6 q-mt-sm">No hay empresas registradas</div><div>Registra primero al cliente y luego su empresa.</div></div></template></q-table>
<q-dialog v-model="dialog"><q-card style="width:820px;max-width:95vw"><q-card-section><div class="section-label">{{editing?'Editar':'Nueva'}} empresa</div><div class="text-h5 text-weight-bold">{{editing?'Actualizar empresa':'Registrar empresa del cliente'}}</div></q-card-section><q-separator/><q-card-section><div class="row q-col-gutter-md"><div class="col-12"><q-select v-model="form.cliente_id" outlined emit-value map-options :options="clients.map(c=>({label:`${c.nombre} · ${c.telefono}`,value:c.id}))" label="Cliente responsable" clearable/></div><div class="col-12 col-sm-7"><q-input v-model="form.nombre_comercial" outlined label="Nombre comercial *"/></div><div class="col-12 col-sm-5"><q-input v-model="form.razon_social" outlined label="Razón social"/></div><div class="col-12"><q-input v-model="form.actividad" outlined label="Actividad o rubro"/></div><div class="col-12 col-sm-4"><q-input v-model="form.telefono" outlined label="Teléfono"/></div><div class="col-12 col-sm-4"><q-input v-model="form.whatsapp" outlined label="WhatsApp"/></div><div class="col-12 col-sm-4"><q-input v-model="form.ciudad" outlined label="Ciudad"/></div><div class="col-12"><q-input v-model="form.direccion" outlined label="Dirección"/></div><div class="col-12"><q-file v-model="logoFile" outlined accept="image/*" label="Logotipo de la empresa (opcional)" clearable/></div><div class="col-12"><q-input v-model="form.observaciones" outlined type="textarea" label="Observaciones"/></div><div class="col-12 col-sm-4"><q-select v-model="form.estado" outlined :options="['prospecto','levantamiento','desarrollo','activo','inactivo']" label="Estado"/></div></div></q-card-section><q-card-actions align="right"><q-btn flat label="Cancelar" v-close-popup/><q-btn color="primary" unelevated :label="editing?'Guardar cambios':'Registrar empresa'" no-caps @click="save"/></q-card-actions></q-card></q-dialog></q-page></template>
