<script setup>
import { onMounted, reactive, ref } from 'vue'
import { useQuasar } from 'quasar'
import { api } from '../boot/axios'
import PageHeader from '../components/PageHeader.vue'
import RowActionsMenu from '../components/RowActionsMenu.vue'
const $q=useQuasar(),rows=ref([]),apps=ref([]),dialog=ref(false),editing=ref(null),loading=ref(false)
const empty=()=>({aplicacion_id:null,empresa_id:null,cliente_id:null,titulo:'',descripcion:'',tipo:'soporte',prioridad:'normal',estado:'abierto'});const form=reactive(empty())
const columns=[{name:'actions',label:'',field:'actions',align:'left'},{name:'codigo',label:'Código',field:'codigo',align:'left'},{name:'titulo',label:'Solicitud',field:'titulo',align:'left'},{name:'aplicacion',label:'Aplicación',field:r=>r.aplicacion?.nombre,align:'left'},{name:'empresa',label:'Empresa',field:r=>r.empresa?.nombre_comercial,align:'left'},{name:'tipo',label:'Tipo',field:'tipo',align:'left'},{name:'prioridad',label:'Prioridad',field:'prioridad',align:'left'},{name:'estado',label:'Estado',field:'estado',align:'left'}]
async function load(){loading.value=true;try{const [m,a]=await Promise.all([api.get('/mantenimientos',{params:{per_page:100}}),api.get('/aplicaciones',{params:{per_page:100}})]);rows.value=m.data.data;apps.value=a.data.data}finally{loading.value=false}}
function open(row=null){editing.value=row;Object.assign(form,empty(),row||{});dialog.value=true}
function appChanged(id){const app=apps.value.find(x=>x.id===id);if(app)form.empresa_id=app.empresa_id}
async function save(){try{editing.value?await api.put(`/mantenimientos/${editing.value.id}`,form):await api.post('/mantenimientos',form);$q.notify({type:'positive',message:'Solicitud de mantenimiento guardada.'});dialog.value=false;load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo guardar.'})}}
function remove(row){$q.dialog({title:'Eliminar solicitud',message:`¿Eliminar ${row.codigo}?`,cancel:true}).onOk(async()=>{await api.delete(`/mantenimientos/${row.id}`);load()})}
onMounted(load)
</script>
<template><q-page class="viti-page"><PageHeader eyebrow="Soporte" title="Mantenimiento" subtitle="Supervisa errores, mejoras, actualizaciones y soporte de las aplicaciones entregadas."><q-btn color="primary" unelevated icon="add" label="Nueva solicitud" no-caps @click="open()"/></PageHeader><q-table flat class="viti-table" :rows="rows" :columns="columns" row-key="id" :loading="loading" :pagination="{rowsPerPage:20,sortBy:'id',descending:true}"><template #body-cell-actions="p"><q-td :props="p"><RowActionsMenu @open="open(p.row)" @edit="open(p.row)" @delete="remove(p.row)"/></q-td></template><template #body-cell-estado="p"><q-td :props="p"><q-badge outline color="primary">{{p.value}}</q-badge></q-td></template><template #no-data><div class="empty-state full-width"><q-icon name="support_agent" size="52px"/><div class="text-h6 q-mt-sm">No hay mantenimientos registrados</div><div>Las solicitudes de soporte aparecerán después de integrar una aplicación.</div></div></template></q-table>
<q-dialog v-model="dialog"><q-card style="width:720px;max-width:94vw"><q-card-section><div class="section-label">Soporte técnico</div><div class="text-h5 text-weight-bold">{{editing?'Editar solicitud':'Registrar mantenimiento'}}</div></q-card-section><q-card-section><q-select v-model="form.aplicacion_id" outlined emit-value map-options :options="apps.map(x=>({label:`${x.nombre} · ${x.empresa?.nombre_comercial}`,value:x.id}))" label="Aplicación *" @update:model-value="appChanged"/><q-input v-model="form.titulo" outlined label="Título *" class="q-mt-md"/><q-input v-model="form.descripcion" outlined type="textarea" label="Descripción *" class="q-mt-md"/><div class="row q-col-gutter-md q-mt-xs"><div class="col-4"><q-select v-model="form.tipo" outlined :options="['soporte','error','mejora','actualizacion','capacitacion']" label="Tipo"/></div><div class="col-4"><q-select v-model="form.prioridad" outlined :options="['baja','normal','alta','urgente']" label="Prioridad"/></div><div class="col-4"><q-select v-model="form.estado" outlined :options="['abierto','en_proceso','en_espera','resuelto','cerrado']" label="Estado"/></div></div></q-card-section><q-card-actions align="right"><q-btn flat label="Cancelar" v-close-popup/><q-btn color="primary" unelevated label="Guardar" no-caps @click="save"/></q-card-actions></q-card></q-dialog></q-page></template>
