<script setup>
import { onMounted, reactive, ref } from 'vue'
import { useQuasar } from 'quasar'
import { useRouter } from 'vue-router'
import { api } from '../boot/axios'
import PageHeader from '../components/PageHeader.vue'
import RowActionsMenu from '../components/RowActionsMenu.vue'
const $q=useQuasar(),router=useRouter(),rows=ref([]),companies=ref([]),clients=ref([]),requests=ref([]),dialog=ref(false),loading=ref(false)
const form=reactive({solicitud_id:null,empresa_id:null,cliente_id:null,nombre:'',descripcion:'',fase:'analisis',estado:'activo',progreso:0,fecha_inicio:new Date().toISOString().slice(0,10)})
const columns=[{name:'actions',label:'',field:'actions',align:'left'},{name:'codigo',label:'Código',field:'codigo',align:'left'},{name:'nombre',label:'Proyecto',field:'nombre',align:'left'},{name:'empresa',label:'Empresa',field:r=>r.empresa?.nombre_comercial,align:'left'},{name:'fase',label:'Fase',field:'fase',align:'left'},{name:'progreso',label:'Progreso',field:'progreso',align:'left'},{name:'estado',label:'Estado',field:'estado',align:'left'}]
async function load(){loading.value=true;try{const [p,e,c,s]=await Promise.all([api.get('/proyectos',{params:{per_page:100}}),api.get('/empresas',{params:{per_page:100}}),api.get('/clientes',{params:{per_page:100}}),api.get('/solicitudes',{params:{per_page:100}})]);rows.value=p.data.data;companies.value=e.data.data;clients.value=c.data.data;requests.value=s.data.data.filter(x=>!x.proyecto)}finally{loading.value=false}}
function open(){Object.assign(form,{solicitud_id:null,empresa_id:null,cliente_id:null,nombre:'',descripcion:'',fase:'analisis',estado:'activo',progreso:0,fecha_inicio:new Date().toISOString().slice(0,10)});dialog.value=true}
function requestChanged(id){const s=requests.value.find(x=>x.id===id);if(s)Object.assign(form,{empresa_id:s.empresa_id,cliente_id:s.cliente_id,nombre:s.titulo,descripcion:s.resumen||''})}
async function save(){try{const {data}=await api.post('/proyectos',form);dialog.value=false;router.push(`/proyectos/${data.data.id}`)}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo crear el proyecto.'})}}
function remove(row){$q.dialog({title:'Eliminar proyecto',message:`¿Eliminar ${row.nombre}?`,cancel:true}).onOk(async()=>{try{await api.delete(`/proyectos/${row.id}`);load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se puede eliminar.'})}})}
onMounted(load)
</script>
<template><q-page class="viti-page"><PageHeader eyebrow="Desarrollo" title="Proyectos" subtitle="Controla el avance desde el análisis hasta la implementación y el mantenimiento."><q-btn color="primary" unelevated icon="add" label="Nuevo proyecto" no-caps @click="open"/></PageHeader><q-table flat class="viti-table" :rows="rows" :columns="columns" row-key="id" :loading="loading" :pagination="{rowsPerPage:20,sortBy:'id',descending:true}"><template #body-cell-actions="p"><q-td :props="p"><RowActionsMenu @open="router.push(`/proyectos/${p.row.id}`)" @edit="router.push(`/proyectos/${p.row.id}`)" @delete="remove(p.row)"/></q-td></template><template #body-cell-progreso="p"><q-td :props="p"><div class="row items-center no-wrap" style="min-width:160px"><q-linear-progress rounded size="9px" :value="p.value/100" color="primary" class="col"/><span class="q-ml-sm">{{p.value}}%</span></div></q-td></template><template #body-cell-estado="p"><q-td :props="p"><q-badge outline color="primary">{{p.value}}</q-badge></q-td></template><template #no-data><div class="empty-state full-width"><q-icon name="account_tree" size="52px"/><div class="text-h6 q-mt-sm">No hay proyectos</div><div>Aprueba una solicitud o crea un proyecto manualmente.</div></div></template></q-table>
<q-dialog v-model="dialog"><q-card style="width:760px;max-width:94vw"><q-card-section><div class="section-label">Nuevo proyecto</div><div class="text-h5 text-weight-bold">Iniciar desarrollo</div></q-card-section><q-separator/><q-card-section><q-select v-model="form.solicitud_id" outlined emit-value map-options clearable :options="requests.map(x=>({label:`${x.codigo} · ${x.titulo}`,value:x.id}))" label="Solicitud aprobada (opcional)" @update:model-value="requestChanged"/><div class="row q-col-gutter-md q-mt-xs"><div class="col-12 col-sm-6"><q-select v-model="form.empresa_id" outlined emit-value map-options :options="companies.map(x=>({label:x.nombre_comercial,value:x.id}))" label="Empresa *"/></div><div class="col-12 col-sm-6"><q-select v-model="form.cliente_id" outlined emit-value map-options :options="clients.map(x=>({label:x.nombre,value:x.id}))" label="Cliente *"/></div><div class="col-12"><q-input v-model="form.nombre" outlined label="Nombre del proyecto *"/></div><div class="col-12"><q-input v-model="form.descripcion" outlined type="textarea" label="Descripción"/></div><div class="col-12 col-sm-4"><q-select v-model="form.fase" outlined :options="['levantamiento','analisis','diseno','desarrollo','beta','pruebas','ajustes','implementacion']" label="Fase"/></div><div class="col-12 col-sm-4"><q-input v-model.number="form.progreso" outlined type="number" min="0" max="100" label="Progreso %"/></div><div class="col-12 col-sm-4"><q-input v-model="form.fecha_inicio" outlined type="date" stack-label label="Inicio"/></div></div></q-card-section><q-card-actions align="right"><q-btn flat label="Cancelar" v-close-popup/><q-btn color="primary" unelevated label="Crear proyecto" no-caps @click="save"/></q-card-actions></q-card></q-dialog></q-page></template>
