<script setup>
import { computed,onMounted,reactive,ref } from 'vue'
import { useQuasar } from 'quasar'
import { api } from '../boot/axios'
import PageHeader from '../components/PageHeader.vue'
const $q=useQuasar();const loading=ref(true);const tab=ref('resumen');const data=ref({resumen:{},atencion:[],catalogo:[],planes:[]});const businesses=ref([]);const projects=ref([]);const provisionDialog=ref(false);const currentCatalog=ref(null);const provision=reactive({empresa_id:null,proyecto_id:null,version:'1.0.0',notas:''});const planDialog=ref(false);const editingPlan=ref(null);const plan=reactive({codigo:'',nombre:'',descripcion:'',precio_proyecto:null,precio_mensual:null,dias_prueba:14,modulos:[],max_usuarios:null,max_aplicaciones:null,activo:true});const assignment=reactive({empresa_id:null,plan_viti_id:null})
const moduleOptions=[{label:'Inicio',value:'inicio'},{label:'Agenda',value:'agenda'},{label:'Órdenes',value:'ordenes'},{label:'Clientes',value:'clientes'},{label:'Equipos',value:'equipos'},{label:'Técnicos',value:'tecnicos'},{label:'Inventario',value:'inventario'},{label:'Pagos',value:'pagos'},{label:'Garantías',value:'garantias'},{label:'Historial y reportes',value:'historial'},{label:'Mensajes',value:'buzon'}]
const cards=[['negocios_activos','Negocios activos','business','primary'],['aplicaciones_activas','Apps activas','apps','positive'],['suscripciones_activas','Suscripciones activas','autorenew','teal'],['suscripciones_suspendidas','Suspendidas','block','negative']]
const businessOptions=computed(()=>businesses.value.map(x=>({label:x.nombre_comercial,value:x.id})));const projectOptions=computed(()=>projects.value.filter(p=>!provision.empresa_id||Number(p.empresa_id)===Number(provision.empresa_id)).map(x=>({label:`${x.codigo} · ${x.nombre}`,value:x.id})));const planOptions=computed(()=>data.value.planes.map(x=>({label:x.nombre,value:x.id})))
function pretty(v){return String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
async function load(){loading.value=true;try{data.value=(await api.get('/saas/resumen')).data.data;const [b,p]=await Promise.all([api.get('/empresas?per_page=100'),api.get('/proyectos?per_page=100')]);businesses.value=b.data.data||[];projects.value=p.data.data||[]}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo cargar el Centro SaaS.'})}finally{loading.value=false}}
function openProvision(app){currentCatalog.value=app;Object.assign(provision,{empresa_id:null,proyecto_id:null,version:'1.0.0',notas:''});provisionDialog.value=true}
async function provisionApp(){try{await api.post(`/saas/catalogo/${currentCatalog.value.id}/provisionar`,provision);provisionDialog.value=false;$q.notify({type:'positive',message:'Aplicación provisionada. Ahora puede pasar por desarrollo, pruebas y entrega.'});await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||Object.values(e.response?.data?.errors||{}).flat()[0]||'No se pudo provisionar.'})}}
function newPlan(){editingPlan.value=null;Object.assign(plan,{codigo:'',nombre:'',descripcion:'',precio_proyecto:null,precio_mensual:null,dias_prueba:14,modulos:[],max_usuarios:null,max_aplicaciones:null,activo:true});planDialog.value=true}
function editPlan(row){editingPlan.value=row;Object.assign(plan,{codigo:row.codigo,nombre:row.nombre,descripcion:row.descripcion||'',precio_proyecto:row.precio_proyecto,precio_mensual:row.precio_mensual,dias_prueba:row.dias_prueba??14,modulos:Array.isArray(row.modulos)?row.modulos:[],max_usuarios:row.max_usuarios,max_aplicaciones:row.max_aplicaciones,activo:row.activo});planDialog.value=true}
async function savePlan(){try{if(editingPlan.value)await api.put(`/saas/planes/${editingPlan.value.id}`,plan);else await api.post('/saas/planes',plan);planDialog.value=false;await load();$q.notify({type:'positive',message:'Plan actualizado.'})}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo guardar el plan.'})}}
async function assignPlan(){try{await api.put(`/saas/negocios/${assignment.empresa_id}/plan`,{plan_viti_id:assignment.plan_viti_id});$q.notify({type:'positive',message:'Plan asignado al negocio.'});await load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo asignar el plan.'})}}
onMounted(load)
</script>
<template><q-page class="viti-page"><PageHeader eyebrow="Plataforma" title="Centro SaaS VITI" subtitle="Controla negocios, aplicaciones, provisionamiento y límites desde una sola capa."/><q-inner-loading :showing="loading"/><div v-if="!loading" class="row q-col-gutter-md"><div v-for="c in cards" :key="c[0]" class="col-12 col-sm-6 col-xl-3"><q-card flat class="viti-card q-pa-lg"><q-icon :name="c[2]" :color="c[3]" size="28px"/><div class="stat-value q-mt-sm">{{data.resumen[c[0]]||0}}</div><div class="stat-label">{{c[1]}}</div></q-card></div></div>
<q-tabs v-model="tab" align="left" no-caps class="q-mt-lg q-mb-md" active-color="primary" indicator-color="primary"><q-tab name="resumen" icon="monitor_heart" label="Operación"/><q-tab name="catalogo" icon="apps" label="Catálogo técnico"/><q-tab name="planes" icon="tune" label="Planes y límites"/></q-tabs><q-tab-panels v-if="!loading" v-model="tab" animated class="transparent">
<q-tab-panel name="resumen" class="q-pa-none"><div class="row q-col-gutter-lg"><div class="col-12 col-lg-7"><q-card flat class="viti-card"><q-card-section><div class="text-h6 text-weight-bold">Necesitan atención</div><div class="text-caption text-grey-6">Entregas, periodos de gracia y suspensiones.</div></q-card-section><q-separator/><q-list v-if="data.atencion?.length" separator><q-item v-for="row in data.atencion" :key="row.app.id"><q-item-section avatar><q-avatar color="primary" text-color="white" :icon="row.ciclo.estado==='lista_entrega'?'key':row.ciclo.estado==='gracia'?'schedule':'block'"/></q-item-section><q-item-section><q-item-label class="text-weight-bold">{{row.app.nombre}}</q-item-label><q-item-label caption>{{row.app.empresa?.nombre_comercial}} · {{row.ciclo.mensaje}}</q-item-label></q-item-section><q-item-section side><q-badge :color="row.ciclo.estado==='suspendida'?'negative':'orange'">{{pretty(row.ciclo.estado)}}</q-badge></q-item-section></q-item></q-list><div v-else class="empty-state">No hay incidencias SaaS pendientes.</div></q-card></div><div class="col-12 col-lg-5"><q-card flat class="viti-card"><q-card-section><div class="text-h6 text-weight-bold">Pulso VITI</div></q-card-section><q-separator/><q-list><q-item><q-item-section>Solicitudes activas</q-item-section><q-item-section side>{{data.resumen.solicitudes_activas||0}}</q-item-section></q-item><q-item><q-item-section>Soportes abiertos</q-item-section><q-item-section side>{{data.resumen.soportes_abiertos||0}}</q-item-section></q-item><q-item><q-item-section>En gracia</q-item-section><q-item-section side>{{data.resumen.suscripciones_gracia||0}}</q-item-section></q-item><q-item><q-item-section>Usuarios de negocio</q-item-section><q-item-section side>{{data.resumen.usuarios_negocio||0}}</q-item-section></q-item></q-list></q-card></div></div></q-tab-panel>
<q-tab-panel name="catalogo" class="q-pa-none"><div class="catalog-grid"><q-card v-for="app in data.catalogo" :key="app.id" flat class="viti-card"><q-card-section><div class="row items-center"><q-avatar color="primary" text-color="white" :icon="app.icono||'apps'"/><div class="q-ml-md"><div class="text-h6 text-weight-bold">{{app.nombre}}</div><div class="text-caption text-grey-6">{{app.tipo}}</div></div></div><div class="text-body2 text-grey-7 q-mt-md">{{app.descripcion}}</div></q-card-section><q-separator/><q-card-actions align="right"><q-btn color="primary" unelevated no-caps icon="add_circle" label="Provisionar" @click="openProvision(app)"/></q-card-actions></q-card></div></q-tab-panel>
<q-tab-panel name="planes" class="q-pa-none"><div class="row q-col-gutter-lg"><div class="col-12 col-lg-7"><q-card flat class="viti-card"><q-card-section class="row items-center"><div><div class="text-h6 text-weight-bold">Planes</div><div class="text-caption text-grey-6">Desarrollo, mensualidad, prueba y módulos de cada nivel.</div></div><q-space/><q-btn color="primary" unelevated no-caps icon="add" label="Nuevo plan" @click="newPlan"/></q-card-section><q-separator/><q-list separator><q-item v-for="p in data.planes" :key="p.id" clickable @click="editPlan(p)"><q-item-section><q-item-label class="text-weight-bold">{{p.nombre}}<span v-if="p.precio_proyecto"> · {{Number(p.precio_proyecto).toFixed(0)}} Bs desarrollo</span></q-item-label><q-item-label caption><span v-if="p.precio_mensual">{{Number(p.precio_mensual).toFixed(0)}} Bs/mes · </span>{{p.dias_prueba??0}} días de prueba · {{p.max_usuarios||'∞'}} usuarios · {{p.max_aplicaciones||'∞'}} apps · {{p.modulos?.length||'Todos los'}} módulos</q-item-label></q-item-section><q-item-section side><q-icon name="edit"/></q-item-section></q-item></q-list></q-card></div><div class="col-12 col-lg-5"><q-card flat class="viti-card"><q-card-section><div class="text-h6 text-weight-bold">Asignar plan</div></q-card-section><q-separator/><q-card-section><q-select v-model="assignment.empresa_id" outlined :options="businessOptions" emit-value map-options label="Negocio"/><q-select v-model="assignment.plan_viti_id" class="q-mt-md" outlined :options="planOptions" emit-value map-options label="Plan"/></q-card-section><q-card-actions align="right"><q-btn color="primary" unelevated no-caps label="Asignar" :disable="!assignment.empresa_id||!assignment.plan_viti_id" @click="assignPlan"/></q-card-actions></q-card></div></div></q-tab-panel></q-tab-panels>
<q-dialog v-model="provisionDialog"><q-card style="width:620px;max-width:94vw"><q-card-section><div class="section-label">Provisionamiento</div><div class="text-h5 text-weight-bold">{{currentCatalog?.nombre}}</div><div class="text-caption text-grey-6">Crea una instancia para un negocio. No la entrega ni inicia una suscripción todavía.</div></q-card-section><q-separator/><q-card-section><q-select v-model="provision.empresa_id" outlined :options="businessOptions" emit-value map-options label="Negocio"/><q-select v-model="provision.proyecto_id" class="q-mt-md" outlined clearable :options="projectOptions" emit-value map-options label="Proyecto relacionado (opcional)"/><q-input v-model="provision.version" class="q-mt-md" outlined label="Versión inicial"/><q-input v-model="provision.notas" class="q-mt-md" outlined type="textarea" label="Notas opcionales"/></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Cancelar" v-close-popup/><q-btn color="primary" unelevated no-caps label="Provisionar" @click="provisionApp"/></q-card-actions></q-card></q-dialog>
<q-dialog v-model="planDialog"><q-card style="width:680px;max-width:94vw"><q-card-section><div class="text-h6 text-weight-bold">{{editingPlan?'Editar plan':'Nuevo plan'}}</div><div class="text-caption text-grey-6">La mensualidad mantiene hosting, plataforma, base de datos, soporte y continuidad del sistema.</div></q-card-section><q-separator/><q-card-section><q-input v-model="plan.nombre" outlined label="Nombre"/><q-input v-model="plan.codigo" class="q-mt-md" outlined label="Código"/><q-input v-model="plan.descripcion" class="q-mt-md" outlined type="textarea" label="Descripción"/><div class="row q-col-gutter-md q-mt-xs"><div class="col-12 col-sm-4"><q-input v-model.number="plan.precio_proyecto" outlined type="number" min="0" clearable label="Desarrollo (Bs)"/></div><div class="col-12 col-sm-4"><q-input v-model.number="plan.precio_mensual" outlined type="number" min="0" clearable label="Mensualidad (Bs)"/></div><div class="col-12 col-sm-4"><q-input v-model.number="plan.dias_prueba" outlined type="number" min="0" max="60" label="Días de prueba"/></div></div><q-select v-model="plan.modulos" class="q-mt-md" outlined multiple use-chips emit-value map-options :options="moduleOptions" label="Módulos incluidos" hint="Vacío significa acceso a todos los módulos."/><div class="row q-col-gutter-md q-mt-xs"><div class="col-6"><q-input v-model.number="plan.max_usuarios" outlined type="number" clearable label="Máx. usuarios"/></div><div class="col-6"><q-input v-model.number="plan.max_aplicaciones" outlined type="number" clearable label="Máx. aplicaciones"/></div></div><q-toggle v-model="plan.activo" class="q-mt-md" label="Plan activo"/></q-card-section><q-card-actions align="right"><q-btn flat no-caps label="Cancelar" v-close-popup/><q-btn color="primary" unelevated no-caps label="Guardar" @click="savePlan"/></q-card-actions></q-card></q-dialog></q-page></template>
<style scoped>.catalog-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:18px}.empty-state{padding:48px 20px;text-align:center;color:var(--viti-muted)}</style>