<script setup>
import { onMounted, reactive, ref } from 'vue'
import { useQuasar } from 'quasar'
import { api } from '../boot/axios'
import PageHeader from '../components/PageHeader.vue'
const $q=useQuasar(),rows=ref([]),dialog=ref(false),editing=ref(null),loading=ref(false)
const empty=()=>({nombre:'',apellido:'',usuario:'',telefono:'',correo:'',rol:'administrador',estado:'activo',password:'',password_confirmation:''});const form=reactive(empty())
const columns=[{name:'actions',label:'',field:'actions',align:'left'},{name:'nombre',label:'Usuario',field:r=>`${r.nombre} ${r.apellido||''}`,align:'left'},{name:'usuario',label:'Acceso',field:'usuario',align:'left'},{name:'telefono',label:'Teléfono',field:'telefono',align:'left'},{name:'rol',label:'Rol',field:'rol',align:'left'},{name:'estado',label:'Estado',field:'estado',align:'left'},{name:'ultimo_acceso',label:'Último acceso',field:'ultimo_acceso',align:'left'}]
async function load(){loading.value=true;try{rows.value=(await api.get('/usuarios')).data.data}finally{loading.value=false}}
function open(row=null){editing.value=row;Object.assign(form,empty(),row||{}, {password:'',password_confirmation:''});dialog.value=true}
async function save(){try{editing.value?await api.put(`/usuarios/${editing.value.id}`,form):await api.post('/usuarios',form);$q.notify({type:'positive',message:'Usuario guardado.'});dialog.value=false;load()}catch(e){$q.notify({type:'negative',message:e.response?.data?.message||'No se pudo guardar.'})}}
onMounted(load)
</script>
<template><q-page class="viti-page"><PageHeader eyebrow="Administración" title="Usuarios internos" subtitle="Equipo de AGR Studio con acceso administrativo, soporte o supervisión."><q-btn color="primary" unelevated icon="person_add" label="Nuevo usuario" no-caps @click="open()"/></PageHeader><q-table flat class="viti-table" :rows="rows" :columns="columns" row-key="id" :loading="loading" :pagination="{rowsPerPage:20,sortBy:'id',descending:true}"><template #body-cell-actions="p"><q-td :props="p"><q-btn flat round dense icon="more_vert"><q-menu><q-list><q-item clickable v-close-popup @click="open(p.row)"><q-item-section avatar><q-icon name="edit"/></q-item-section><q-item-section>Editar</q-item-section></q-item></q-list></q-menu></q-btn></q-td></template><template #body-cell-estado="p"><q-td :props="p"><q-badge outline color="primary">{{p.value}}</q-badge></q-td></template></q-table>
<q-dialog v-model="dialog"><q-card style="width:720px;max-width:94vw"><q-card-section><div class="section-label">Usuario interno</div><div class="text-h5 text-weight-bold">{{editing?'Editar acceso':'Crear acceso'}}</div></q-card-section><q-card-section><div class="row q-col-gutter-md"><div class="col-6"><q-input v-model="form.nombre" outlined label="Nombre *"/></div><div class="col-6"><q-input v-model="form.apellido" outlined label="Apellido"/></div><div class="col-6"><q-input v-model="form.usuario" outlined label="Usuario *"/></div><div class="col-6"><q-input v-model="form.telefono" outlined label="Teléfono"/></div><div class="col-12"><q-input v-model="form.correo" outlined label="Correo opcional"/></div><div class="col-6"><q-select v-model="form.rol" outlined :options="['superadmin','administrador','soporte']" label="Rol"/></div><div class="col-6"><q-select v-model="form.estado" outlined :options="['activo','inactivo']" label="Estado"/></div><div class="col-6"><q-input v-model="form.password" outlined type="password" :label="editing?'Nueva contraseña (opcional)':'Contraseña *'"/></div><div class="col-6"><q-input v-model="form.password_confirmation" outlined type="password" label="Confirmar contraseña"/></div></div></q-card-section><q-card-actions align="right"><q-btn flat label="Cancelar" v-close-popup/><q-btn color="primary" unelevated label="Guardar" no-caps @click="save"/></q-card-actions></q-card></q-dialog></q-page></template>
